# Generated by Django 4.2 on 2023-04-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0003_recipe_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=7)),
                ('unit', models.CharField(max_length=20)),
                ('related_ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.ingredient')),
                ('related_recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.recipe')),
            ],
        ),
    ]
