# Generated by Django 4.2 on 2023-04-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0007_remove_recipe_ingredient_related_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='related_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='related_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.recipe'),
        ),
    ]
