# Generated by Django 4.2 on 2023-04-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0016_remove_recipe_preparation_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_duration',
        ),
    ]
