# Generated by Django 4.2 on 2023-04-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0024_recipe_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_duration',
        ),
    ]
