# Generated by Django 4.2 on 2023-04-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0028_remove_process_executed_once_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_schedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='utensils',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('related_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.process')),
            ],
        ),
    ]
