# Generated by Django 4.2 on 2023-04-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0006_remove_recipe_ingredient_related_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='related_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='related_recipe',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='related_ingredient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='related_recipe',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.recipe'),
            preserve_default=False,
        ),
    ]
