# Generated by Django 4.2 on 2023-04-05 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_manager', '0008_alter_recipe_ingredient_related_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image_user', to=settings.AUTH_USER_MODEL)),
                ('related_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.recipe')),
            ],
        ),
    ]
