# Generated by Django 4.2 on 2023-04-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_manager', '0010_recipe_image_delete_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_step_user', to=settings.AUTH_USER_MODEL)),
                ('related_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.recipe')),
            ],
        ),
    ]
