# Generated by Django 4.2 on 2023-04-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0012_recipe_difficulty_recipe_preparation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_duration',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_duration',
            field=models.DurationField(default=None, null=True),
        ),
    ]
