# Generated by Django 4.2 on 2023-04-08 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_manager', '0021_remove_process_step_related_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='process_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
