# Generated by Django 4.2 on 2023-04-08 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0022_process_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_duration',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='process',
            name='wait_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='process',
            name='work_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
