# Generated by Django 4.2 on 2023-04-08 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0023_remove_recipe_preparation_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
