# Generated by Django 4.2 on 2023-04-08 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0025_remove_recipe_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='executed_once',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='start_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
