# Generated by Django 4.2 on 2023-04-14 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_manager', '0032_utensils_owner_alter_recipe_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_schedule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
