# Generated by Django 4.2 on 2023-04-14 09:02

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0038_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=image_cropping.fields.ImageCropField(default='images/placeholder/recipe.png', upload_to='images/dynamic'),
        ),
    ]
