# Generated by Django 4.2 on 2023-04-21 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings_manager', '0003_settings_notification_pushover_enabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings_notification',
            new_name='SettingsNotification',
        ),
    ]
