# Generated by Django 4.2 on 2023-04-16 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_manager', '0039_alter_recipe_image'),
        ('batches', '0004_batch_related_recipe_batch_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('execution_datetime', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_user', to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('related_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.process')),
            ],
        ),
    ]
