# Generated by Django 4.2 on 2023-04-18 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_finished_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
