# Generated by Django 4.2 on 2023-04-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0010_alter_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
