# Generated by Django 4.2 on 2023-04-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0012_execution_notification_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finished_Execution',
        ),
    ]
