# Generated by Django 4.2 on 2023-04-26 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0013_delete_finished_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_user',
                                   to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
            ],
        ),
    ]
