# Generated by Django 4.2 on 2023-04-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('batches', '0014_alter_batch_start_date_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='jar_image',
            field=models.ImageField(default=None, upload_to='images'),
            preserve_default=False,
        ),
    ]
