# Generated by Django 4.2 on 2023-04-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('batches', '0015_qrcode_jar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='jar_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
