# Generated by Django 4.2 on 2023-05-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('batches', '0017_alter_qrcode_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='batches.batch'),
        ),
    ]
