# Generated by Django 4.2 on 2023-04-16 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0039_alter_recipe_image'),
        ('batches', '0003_batch_description_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='related_recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe_manager.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
