# Generated by Django 4.2 on 2023-04-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_notification_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification_credentials',
        ),
    ]
