# Generated by Django 4.2 on 2023-04-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_delete_notification_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Execution',
            fields=[
                ('execution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='batches.execution')),
            ],
            bases=('batches.execution',),
        ),
    ]
