# Generated by Django 4.2 on 2023-04-18 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0009_alter_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 22, 59, 50, 769196, tzinfo=datetime.timezone.utc)),
        ),
    ]
