# Generated by Django 4.2 on 2023-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0011_alter_batch_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
